# Generated by Django 5.2 on 2025-04-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ciphertool',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='ciphertool',
            name='icon',
            field=models.CharField(default='fa-tools', max_length=50),
        ),
        migrations.AddField(
            model_name='ciphertool',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ciphertool',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.category'),
        ),
    ]
